### ISSUE TITLE
How to Write a Git Commit Message 번역

### ISSUE THREAD

**Issue by haruair** [weirdmeetup/monad-guide-kr#7]
[How to Write a Git Commit Message](https://github.com/weirdmeetup/translate/blob/master/articles/2014-08-31-git-commit.md) [원본](http://chris.beams.io/posts/git-commit/)의 공동 번역을 진행합니다.
## 담당 범위
- 서문 @chiyodad
- 1~4 @haruair
- 5~7, 팁 @item4

**Comment by item4** [comment]
초벌번역 올렸습니다 #8

**Comment by ujuc** [comment]
우와..~~~~~~~~

퇴고는 언제쯤?

**Comment by majorika** [comment]
세군데 정도 번역이 안 된 문장이 있는 것 같은데요. 혹시 번역하시다가 누락 된 것이 아닌가 싶습니다!

1.

> The contributors to these repositories know that a well-crafted git commit message is the best way to communicate context about a change to fellow developers (and indeed to their future selves). A diff will tell you what changed, but only the commit message can properly tell you why. Peter Hutterer makes this point well:
> 
> 이 저장소들의 기여자들은 잘 다듬어진 커밋 메시지는 변경사항에 대한 컨텍스트 를 동료 개발자(뿐만 아니라 실제로 미래의 자기 자신)와 공유할 수 있는 최고의 수단임을 잘 알고 있습니다.

2.

> A project's long-term success rests (among other things) on its maintainability, and a maintainer has few tools more powerful than his project's log. It's worth taking the time to learn how to care for one properly. What may be a hassle at first soon becomes habit, and eventually a source of pride and productivity for all involved.
> 
> 한 프로젝트가 오랜 기간 동안 성공할 수 있을지의 여부는 (다른 것들 중에서)유지보수성에 달려있고, 유지보수를 하는 사람에게 그의 프로젝트 로그보다 더 강력한 도구는 별로 없다.

3.

> Style. Markup syntax, wrap margins, grammar, capitalization, punctuation. Spell these things out, remove the guesswork, and make it all as simple as possible. The end result will be a remarkably consistent log that's not only a pleasure to read but that actually does get read on a regular basis.
> 
> 스타일 마크업 문법, 여백 감싸기, 문법, 대문자 사용, 구두점. 이것들을 문서화 시키고 추측을 제거하고, 가능한 한 간단하게 만들어야 한다.

**Comment by chiyodad** [comment]
@majorika 앗 감사합니다. 채워넣을게요.

**Comment by item4** [comment]
일단 지금 3명의 어조가 약간씩 다른 것 같은데 통일을 해야할 것 같습니다.

저는 개인적으로 제가 번역한 부분의 5번 단락이 커밋 제목을 명령조로 할 것에 대한 이야기를 다루고 있고, 해당 단락에서 '각 룰의 명칭도 명령조이다' 라는 언급이 있으므로 단락의 제목은 명령조로, 나머지는 제목보다 부드러운 문체로 가야 혼란이 덜하지 않을까 싶습니다.

**Comment by haruair** [comment]
현재 모든 PR을 반영했습니다. 맡은 분량과 상관 없이 한번 훑어보시고 어색한 표현이나 놓친 부분을 찾아보는 것으로 교정을 마무리하면 좋겠습니다. 수정할 부분이 없는 경우에도 내용 모두 확인했다고 덧글 남겨주시면 더 쉽게 진행할 수 있을 것 같습니다.

수정 사항 일괄 반영 후에 팀블로그를 통해 크레딧과 함께 포스팅하는 것으로 이 이슈를 마무리하겠습니다. 참여해주신 모든 분들께 감사 말씀 드립니다. :smile:

**Comment by item4** [comment]
1. 1-4 위에 있는 toc가 취합이 안 되어있습니다.
2. 1-4의 제목이 5의 룰을 따라야할지 의논이 필요해보입니다

(@haruair님 #16 PR로 수정됨)

**Comment by item4** [comment]
사실 처음 @chiyodad 님과 번역을 이야기할때는 개인 블로그에 올리는게 목적이었는데 참여 인원수가 너무 많아져서 이모 팀블로그에만 올라가는게 맞는거 아닐까 하는 생각을 하고 있습니다. 다들 개인 블로그에 올리실건가요? (질문)

**Comment by ujuc** [comment]
@item4 전 아뇨...

**Comment by chiyodad** [comment]
전 미디엄에만 올릴게요

**Comment by item4** [comment]
## (현재까지) 참여자 명단
- [@chiyodad](https://github.com/chiyodad/)
- [@haruair](https://github.com/haruair/)
- [@item4](https://github.com/item4/)
- [@majorika](https://github.com/majorika/)
- [@minieetea](https://github.com/minieetea/)
- [@riseshia](https://github.com/riseshia/)
- [@ujuc](https://github.com/ujuc/)

``` markdown
## 참여자 명단

- [@chiyodad](https://github.com/chiyodad/)
- [@haruair](https://github.com/haruair/)
- [@item4](https://github.com/item4/)
- [@majorika](https://github.com/majorika/)
- [@minieetea](https://github.com/minieetea/)
- [@riseshia](https://github.com/riseshia/)
- [@ujuc](https://github.com/ujuc/)
```

**Comment by haruair** [comment]
너무 신경을 못썼네요! @item4 님 PR을 마지막으로 이슈 닫으려고 합니다. 포스트로 올리실 분은 크레딧 포함해서 올려주시고 포스팅 후에 주소 알려주시면 널리 퍼뜨리도록 하겠습니다. 모두 수고하셨습니다. :)
